#theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0

#permalink: /:categories/:year/:month/:day/:title

exclude: ["README.md", "License.md"]
highlighter: rouge

title: Portfolio
description: Homepage for my profile and all things tech related.

author:
    name: Trevor Taylor
    email: ttaylor@talentpath.com
    github: Trevis42

show_downloads: false;

# NOTE: Replacing this next line with your own URL
production_url: https://trevis42.github.io

JB:
    version: 0.3.0

BASE_PATH: https://trevis42.github.io

archive_path: nil
categories_path: nil
tags_path: nil
atom_path: nil
rss_path: nil

comments:
    provider: false

analytics:
    provider: false

sharing:
    provider: false
